### ISSUE TITLE
Broken GET /courses/:id/roster

### ISSUE THREAD

**Issue by TravisWhitehead** [osu-cs493-sp19/final-project-mohamed#7]
@jcorme I'm not sure why the class is considered undefined, `enrolledStudents(id)` is a static member of the class...
```
api_1       | TypeError: Cannot read property 'enrolledStudents' of undefined
api_1       |     at Course.enrolledStudents (/usr/src/app/models/course.js:16:32)
api_1       |     at router.get (/usr/src/app/api/courses.js:214:35)
api_1       |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
https://github.com/osu-cs493-sp19/final-project-mohamed/blob/0a1920a808b2c86534ca4773360ceffdea9c69d3/models/course.js#L15-L17

**Comment by TravisWhitehead** [comment]
Fixed by #8
